### ISSUE TITLE
Request for Explanation on Implementation

### ISSUE THREAD

**Issue by RoderickJDunn** [ka-weihe/fastest-levenshtein#6]
Thank you for this library- I'm very happy with the results so far. 

I wonder if you wouldn't mind answering some questions I have about the algorithm you used. I understand the general concept behind Levenshtein distance, and have read a fair amount on the Bitap algorithm, and a little on Myers', but I'm really curious to know more about how this implementation works, as I'm having trouble making sense of the source. 

I'm most interested in the myers_32 function. From what I can tell, it first builds `peq`, which maps each character in stringA to a mask of that char's positions in the string. Then it loops through each character in stringB, decreasing or increasing the edit distance `sc` according to various conditions. I'd really appreciate a summary of what each of the variables used by this loop represent. I'd even be grateful if you could let me know what each var stands for (`eq`, `pv`, `mv`, `xv`, `sc`).

Thanks!

**Comment by ka-weihe** [comment]
The implementation is based on Myers' bit-vector algorithm for approximate string matching. I think [this paper](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.332.9395&rep=rep1&type=pdf) by Myers himself describes it the best. It makes perfect sense that you have trouble making sense of the source because the performance was a much higher priority than readability. Most of the variables don't have the same meaning as in the paper, because I excluded some and combined some to make it faster. I hope this helps :slightly_smiling_face:

**Comment by RoderickJDunn** [comment]
Great, I'll give the paper a read. Thanks again

**Comment by fabiospampinato** [comment]
@RoderickJDunn @ka-weihe do you have the link to the paper mentioned?

**Comment by fabiospampinato** [comment]
It might be this one: https://ur.booksc.eu/dl/18778807/05b470

**Comment by RoderickJDunn** [comment]
@fabiospampinato your link isn't working for me for some reason. This was the original link he provided
https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.332.9395&rep=rep1&type=pdf
